apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: mario
  name: mario

spec:
  selector:
    matchLabels:
      app: mario

  template:
    metadata:
      labels:
        app: mario

    spec:
      containers:
        - image: ghcr.io/wgbh-mla/mario:pr-28
          imagePullPolicy: Always
          name: mario
          command: ['/app/mario/pipelines/runner.py']
          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
            requests:
              cpu: 200m
              memory: 100Mi
          envFrom:
            - secretRef:
                name: mario-secret
          volumeMounts:
            - mountPath: /root/.cache/
              name: cache
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: cache-pvc
